var data = {
  "service": "Housing estate developments - aka new builds",
  "last-updated": "1 August 2025",
  "userjourneys": [            
    {
      "title": "View housing developments - successful private beta service - minimum viable service",
      "path": [{
        "caption": "Housing developments list",  
        "imgref": "images/1/1-list-of-housing-developments.png",
        "note": [
        	"all housing developments.  in future this would be searchable, regional, etc."
        ]
      },{
        "caption": "Housing development",
        "imgref": "images/1/2-housing-development.png",
        "note": "development homepage"
      },{
        "caption": "plots",
        "imgref": "images/1/3-list-of-plots-on-development-short.png",
        "note": [
          "not all plots have plans, or have had their boundaires checked, as developers evolve estates as they build them. They often submit partial plans to HMLR to check.",
          "plots start without an address",
          "plot list is generated by caseworkers when checking the plan (Estate Plan approval).",
          "behind the scenes a new simple 'Devs' spreadsheet tracks plan and plot statuses and the website automatically publishes the data from the sheet.",
          "plot boundaries - skeleton title plans and registers can also be automatically created for each plot - each time the estate plan is checked"
        ]
      },{
        "caption": "plots",
        "imgref": "images/1/4-list-of-plots-on-development-addresses-short.png",
        "note": [
					"plots with addresses, development is advanced, approaching sale"
        ]
      },{
        "caption": "estate plan, pdf supplied by the developer",
        "imgref": "images/1/5-plan.png",
        "note": [
          "checked by HM Land Regsistry (Estate Plan Approval - EPA)",
          "URL to development page added to PDF plan, so if downloaded (and saved or shared), people will always return to the latest (checked) information"
        ]
      },{
        "caption": "example plots plan",
        "imgref": "images/1/6-plot-plan.png",
        "note": [
          "Conveyancers are not geo specialists, and often print maps (taken form other people) draw on by hand, and re-scan to sumbit applications.  These are error laden and required caseworkes to digitze",
          "Applying from this page, with this data ensures everyone is using the correct data in a digital format, no need for the comveyancer to supply the extent - we already have it"
        ]
      }
      ]
    },{
      "title": "View housing developments - alpha further explorations",
      "path": [{
        "caption": "Googling for homes",  
        "imgref": "images/2/1-google-results-westway.png",
        "note": [
        	"a user probably is searching for homes, search results include Housing developments Government know about"
        ]
      },{
        "caption": "Housing developments list",
        "imgref": "images/2/2-housing-developments.png",
        "note": "all housing developments.  in future this would be searchable, regional, etc"
      },{
        "caption": "Housing development homepage",
        "imgref": "images/2/3-housing-developments-westway.png",
        "note": [
          "a page per housing development on GOV.UK",
        	"access to current plans - as supplied by the developer.  single source of latest plan, always the latest plan for all parties to refer to",
        	"page could include what else Gov - central and local know about this development"]
      },{
        "caption": "plot list",
        "imgref": "images/2/4-plan-and-plots.png",
        "note": [
          "view the estate plan, and the plots with their status",
          "plots start without an address, and as they are built and HMLR draft title plans, the address is updated"
        ]
      },{
        "caption": "plot plan and status",
        "imgref": "images/2/5-plot-plan.png",
        "note": [
          "view individual plot plans - whose boundaries have been checked by HMLR",
          "view status: everything HMLR (and Gpvernment) know about this plot/title",
          "view information required for HMLR enquiries and applications or include option to make an application, such as reserve priority (OS2)"
        ]
      },{
        "caption": "Notifications",
        "imgref": "images/2/6-notifications.png",
        "note": [
          "be notified if the status or information about estate plan (or plot - plot page not shown) changes"
        ]
      }
      ]
    },{
      "title": "Estate plan approval - alpha further explorations",
      "path": [{
        "caption": "title",  
        "imgref": "images/3/x.png",
        "note": [
        	""
        ]
      },{
        "caption": "title",
        "imgref": "images/3/x.png",
        "note": ""
      }
      ]
    },{
      "title": "other bits - scope of servcie in wider journey, emails, notifications, mobile",
      "path": [{
        "caption": "scope of service - information about development phase",  
        "imgref": "images/4/service-scope.png",
        "note": [
        	"best place and way to solve problems during development to sale space - view what HMLR know about plans and titles, and their status",
        	"solves problem of too many copies of information, in documents, circulating between all parties",
        	"make information about the estate paln and pot more up to date with the real world, processes Gov checks more easily and enables people like OS and conveyancers to take action at better times"
        ]
      },{
        "caption": "selection of real beta pages, and some alaph thinking",
        "imgref": "images/4/example.png",
        "note": ""
      },{
        "caption": "beta - estate information site - on mobile",
        "imgref": "images/4/mobile-view-estate.png",
        "note": ""
      },{
        "caption": "alpha - digital service for check development plan (EPA) - on mobile",
        "imgref": "images/4/mobile-view-start-epa.png",
        "note": "digital service to check estate plan (EPA)"
      }

      ]
    }
  ]}
